# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: Build Project@2
  inputs:
    command: 'build'
    projects: '**/*.sln'

- task: Publish Project@2
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '**/ConsoleApp1.csproj'
    arguments: '-r linux-arm'
    zipAfterPublish: false

- task: Clone Lab Deploy @2
  inputs:
    script: 'git clone "https://NetCorePi@dev.azure.com/NetCorePi/Lab/_git/LabDeploy" "Deploy"'
    workingDirectory: '$(Build.ArtifactStagingDirectory)'

- task: Copy Artifacts @2
  displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)/Deploy'
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'
    Contents: |
     **/linux-arm/publish/*
     !.git/**/*
    TargetFolder: '$(Build.ArtifactStagingDirectory)/Deploy'

- task: Push Lab Deploy @2
  inputs:
    script: |
      git config --global user.email "michael.payne@gilmond.com"
      git config --global user.name "Michael Payne"
      git add .
      git commit -m "Latest Deploy" -a
      git push
    workingDirectory: '$(Build.ArtifactStagingDirectory)/Deploy'

- task: GitHubRelease@1
  inputs:
    gitHubConnection: 'Git Hub'
    repositoryName: 'hellisafish/Lab'
    action: 'create'
    target: '$(Build.SourceVersion)'
    tagSource: 'gitTag'
    changeLogCompareToRelease: 'lastFullRelease'
    changeLogType: 'commitBased'